// Auto-generated by .claude/skills/shadcn-ui-design/scripts/build-tokens-data.py — do not edit by hand.
// Source: .claude/skills/shadcn-ui-design/references/variables-export.json

export type FloatToken = {
  name: string;
  value: number;
  alias: string | null;
};

export const opacityTokens: FloatToken[] = [
  { name: "0", value: 0, alias: "0" },
  { name: "5", value: 5, alias: "5" },
  { name: "10", value: 10, alias: "10" },
  { name: "15", value: 15, alias: "15" },
  { name: "20", value: 20, alias: "20" },
  { name: "25", value: 25, alias: "25" },
  { name: "30", value: 30, alias: "30" },
  { name: "35", value: 35, alias: "35" },
  { name: "40", value: 40, alias: "40" },
  { name: "45", value: 45, alias: "45" },
  { name: "50", value: 50, alias: "50" },
  { name: "55", value: 55, alias: "55" },
  { name: "60", value: 60, alias: "60" },
  { name: "65", value: 65, alias: "65" },
  { name: "70", value: 70, alias: "70" },
  { name: "75", value: 75, alias: "75" },
  { name: "80", value: 80, alias: "80" },
  { name: "85", value: 85, alias: "85" },
  { name: "90", value: 90, alias: "90" },
  { name: "95", value: 95, alias: "95" },
  { name: "100", value: 100, alias: "100" },
];

export const strokeWidthTokens: FloatToken[] = [
  { name: "stroke-0,5", value: 0.5, alias: "0,5" },
  { name: "stroke-0,75", value: 0.75, alias: "0,75" },
  { name: "stroke-1", value: 1, alias: "1" },
  { name: "stroke-1,25", value: 1.25, alias: "1,25" },
  { name: "stroke-1,5", value: 1.5, alias: "1,5" },
  { name: "stroke-1,75", value: 1.75, alias: "1,75" },
  { name: "stroke-2", value: 2, alias: "2" },
  { name: "stroke-2,25", value: 2.25, alias: "2,25" },
  { name: "stroke-2,5", value: 2.5, alias: "2,5" },
  { name: "stroke-2,75", value: 2.75, alias: "2,75" },
  { name: "stroke-3", value: 3, alias: "3" },
];

