// Auto-generated by .claude/skills/shadcn-ui-design/scripts/build-tokens-data.py — do not edit by hand.
// Source: .claude/skills/shadcn-ui-design/references/variables-export.json

export type TokenCollectionSummary = {
  name: string;
  count: number;
  type: string;
};

export const collectionSummary: TokenCollectionSummary[] = [
  { name: "shadcn/ui", count: 35, type: "COLOR" },
  { name: "tw/colors", count: 244, type: "COLOR" },
  { name: "token", count: 88, type: "FLOAT" },
  { name: "border-radius", count: 150, type: "FLOAT" },
  { name: "border-width", count: 45, type: "FLOAT" },
  { name: "font", count: 45, type: "STRING" },
  { name: "height", count: 24, type: "FLOAT" },
  { name: "gap", count: 102, type: "FLOAT" },
  { name: "max-height", count: 35, type: "FLOAT" },
  { name: "margin", count: 245, type: "FLOAT" },
  { name: "opacity", count: 21, type: "FLOAT" },
  { name: "fontUse", count: 2, type: "STRING" },
  { name: "padding", count: 245, type: "FLOAT" },
  { name: "space", count: 68, type: "FLOAT" },
  { name: "stroke-width", count: 11, type: "FLOAT" },
  { name: "max-width", count: 51, type: "FLOAT" },
  { name: "rdx/colors", count: 396, type: "COLOR" },
];

export const totalTokens = 1807;
