// Auto-generated by .claude/skills/shadcn-ui-design/scripts/build-tokens-data.py — do not edit by hand.
// Source: .claude/skills/shadcn-ui-design/references/variables-export.json

export type FontToken = {
  name: string;
  category: string;
  value: string | number;
  type: 'STRING' | 'FLOAT';
};

export const fontTokens: FontToken[] = [
  { name: "family/sans", category: "family", value: "Inter", type: "STRING" },
  { name: "size/xs", category: "size", value: 12, type: "FLOAT" },
  { name: "style/italic", category: "style", value: "italic", type: "STRING" },
  { name: "style/not-italic", category: "style", value: "normal", type: "STRING" },
  { name: "size/sm", category: "size", value: 14, type: "FLOAT" },
  { name: "size/base", category: "size", value: 16, type: "FLOAT" },
  { name: "size/lg", category: "size", value: 18, type: "FLOAT" },
  { name: "size/xl", category: "size", value: 20, type: "FLOAT" },
  { name: "size/2xl", category: "size", value: 24, type: "FLOAT" },
  { name: "size/3xl", category: "size", value: 30, type: "FLOAT" },
  { name: "size/4xl", category: "size", value: 36, type: "FLOAT" },
  { name: "size/5xl", category: "size", value: 48, type: "FLOAT" },
  { name: "size/6xl", category: "size", value: 60, type: "FLOAT" },
  { name: "size/7xl", category: "size", value: 72, type: "FLOAT" },
  { name: "size/8xl", category: "size", value: 96, type: "FLOAT" },
  { name: "size/9xl", category: "size", value: 128, type: "FLOAT" },
  { name: "family/mono", category: "family", value: "Geist Mono", type: "STRING" },
  { name: "weight/thin", category: "weight", value: 100, type: "FLOAT" },
  { name: "weight/extralight", category: "weight", value: 200, type: "FLOAT" },
  { name: "weight/light", category: "weight", value: 300, type: "FLOAT" },
  { name: "weight/normal", category: "weight", value: 400, type: "FLOAT" },
  { name: "weight/medium", category: "weight", value: 500, type: "FLOAT" },
  { name: "weight/semibold", category: "weight", value: 600, type: "FLOAT" },
  { name: "weight/bold", category: "weight", value: 700, type: "FLOAT" },
  { name: "weight/extrabold", category: "weight", value: 800, type: "FLOAT" },
  { name: "weight/black", category: "weight", value: 900, type: "FLOAT" },
  { name: "leading/3", category: "leading", value: 12, type: "FLOAT" },
  { name: "leading/4", category: "leading", value: 16, type: "FLOAT" },
  { name: "leading/5", category: "leading", value: 20, type: "FLOAT" },
  { name: "leading/6", category: "leading", value: 24, type: "FLOAT" },
  { name: "leading/7", category: "leading", value: 28, type: "FLOAT" },
  { name: "leading/8", category: "leading", value: 32, type: "FLOAT" },
  { name: "leading/9", category: "leading", value: 36, type: "FLOAT" },
  { name: "leading/10", category: "leading", value: 40, type: "FLOAT" },
  { name: "leading/12", category: "leading", value: 48, type: "FLOAT" },
  { name: "leading/15", category: "leading", value: 60, type: "FLOAT" },
  { name: "leading/16", category: "leading", value: 72, type: "FLOAT" },
  { name: "leading/24", category: "leading", value: 96, type: "FLOAT" },
  { name: "leading/32", category: "leading", value: 128, type: "FLOAT" },
  { name: "tracking/tighter", category: "tracking", value: -0.800000011920929, type: "FLOAT" },
  { name: "tracking/tight", category: "tracking", value: -0.4000000059604645, type: "FLOAT" },
  { name: "tracking/normal", category: "tracking", value: 0, type: "FLOAT" },
  { name: "tracking/wide", category: "tracking", value: 0.4000000059604645, type: "FLOAT" },
  { name: "tracking/wider", category: "tracking", value: 0.800000011920929, type: "FLOAT" },
  { name: "tracking/widest", category: "tracking", value: 1.600000023841858, type: "FLOAT" },
];

export const fontUseTokens: FontToken[] = [
  { name: "San Serif", category: "use", value: "IBM Plex Sans Thai", type: "STRING" },
  { name: "Serif", category: "use", value: "SF Thonburi", type: "STRING" },
];
