"""Generate typed TS data files from variables-export.json.

Reads .claude/skills/shadcn-ui-design/references/variables-export.json
and writes structured data to lib/tokens/*.ts. The docs pages import
from there, so they never touch the raw JSON.

Run from project root:
    python .claude/skills/shadcn-ui-design/scripts/build-tokens-data.py
"""
from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]  # project root (script lives 5 levels deep: .claude/skills/shadcn-ui-design/scripts/file.py)
JSON_PATH = ROOT / ".claude/skills/shadcn-ui-design/references/variables-export.json"
OUT_DIR = ROOT / "lib/tokens"

HEADER = (
    "// Auto-generated by .claude/skills/shadcn-ui-design/scripts/build-tokens-data.py — do not edit by hand.\n"
    "// Source: .claude/skills/shadcn-ui-design/references/variables-export.json\n\n"
)


def rgba_to_hex(c: dict) -> str:
    r = round(c["r"] * 255)
    g = round(c["g"] * 255)
    b = round(c["b"] * 255)
    a = c.get("a", 1)
    if a < 0.999:
        return f"#{r:02X}{g:02X}{b:02X}{round(a * 255):02X}"
    return f"#{r:02X}{g:02X}{b:02X}"


def rgba_to_css(c: dict) -> str:
    r = round(c["r"] * 255)
    g = round(c["g"] * 255)
    b = round(c["b"] * 255)
    a = c.get("a", 1)
    if a < 0.999:
        return f"rgba({r}, {g}, {b}, {round(a, 3)})"
    return f"rgb({r}, {g}, {b})"


def js_string(s: str | None) -> str:
    if s is None:
        return "null"
    return json.dumps(s)


def load_collections() -> dict[str, list[dict]]:
    data = json.loads(JSON_PATH.read_text())
    out: dict[str, list[dict]] = defaultdict(list)
    for v in data["variables"]:
        out[v["collectionName"]].append(v)
    return out


# ----------------------- colors -----------------------


def build_colors(collections: dict[str, list[dict]]) -> str:
    out = [HEADER]
    out.append("export type ColorValue = {\n  hex: string;\n  css: string;\n  alias: string | null;\n  aliasCollection: string | null;\n};\n\n")

    # shadcn semantic (4 modes)
    out.append("export type ShadcnSemanticToken = {\n  name: string;\n  light: ColorValue;\n  dark: ColorValue;\n  primary: ColorValue;\n  secondary: ColorValue;\n};\n\n")

    def mode_value(v: dict, mode: str) -> str:
        m = v["valuesByMode"][mode]
        val = m["value"]
        # Could be alias-only (color reference) — Figma resolves; here it's always {r,g,b,a}
        hex_v = rgba_to_hex(val)
        css_v = rgba_to_css(val)
        alias = m.get("alias")
        ac = m.get("aliasCollection")
        return f"{{ hex: {js_string(hex_v)}, css: {js_string(css_v)}, alias: {js_string(alias)}, aliasCollection: {js_string(ac)} }}"

    out.append("export const shadcnTokens: ShadcnSemanticToken[] = [\n")
    for v in collections["shadcn/ui"]:
        out.append(
            f"  {{ name: {js_string(v['name'])}, light: {mode_value(v, 'Light mode')}, dark: {mode_value(v, 'Dark mode')}, primary: {mode_value(v, 'Primary')}, secondary: {mode_value(v, 'Secondary')} }},\n"
        )
    out.append("];\n\n")

    # Single-mode color helper
    out.append("export type PrimitiveColorToken = {\n  name: string;\n  step: string;\n  hex: string;\n  css: string;\n};\n\n")

    def emit_palette(name: str, varname: str, collection_key: str) -> None:
        out.append(f"export const {varname}: Record<string, PrimitiveColorToken[]> = {{\n")
        groups: dict[str, list[dict]] = defaultdict(list)
        for v in collections[collection_key]:
            n = v["name"]
            if "/" in n:
                family, step = n.split("/", 1)
            else:
                family, step = n, n
            groups[family].append({**v, "step": step})

        for family, items in groups.items():
            out.append(f"  {js_string(family)}: [\n")
            for it in items:
                val = it["valuesByMode"]["Mode 1"]["value"]
                hex_v = rgba_to_hex(val)
                css_v = rgba_to_css(val)
                out.append(
                    f"    {{ name: {js_string(it['name'])}, step: {js_string(it['step'])}, hex: {js_string(hex_v)}, css: {js_string(css_v)} }},\n"
                )
            out.append("  ],\n")
        out.append("};\n\n")

    emit_palette("Tailwind", "twColors", "tw/colors")
    emit_palette("Radix", "rdxColors", "rdx/colors")

    return "".join(out)


# ----------------------- typography -----------------------


def build_typography(collections: dict[str, list[dict]]) -> str:
    out = [HEADER]
    out.append("export type FontToken = {\n  name: string;\n  category: string;\n  value: string | number;\n  type: 'STRING' | 'FLOAT';\n};\n\n")

    out.append("export const fontTokens: FontToken[] = [\n")
    for v in collections["font"]:
        n = v["name"]
        category = n.split("/")[0] if "/" in n else "other"
        val = v["valuesByMode"]["Mode 1"]["value"]
        val_str = js_string(val) if v["resolvedType"] == "STRING" else str(val)
        out.append(
            f"  {{ name: {js_string(n)}, category: {js_string(category)}, value: {val_str}, type: {js_string(v['resolvedType'])} }},\n"
        )
    out.append("];\n\n")

    out.append("export const fontUseTokens: FontToken[] = [\n")
    for v in collections["fontUse"]:
        val = v["valuesByMode"]["Mode 1"]["value"]
        val_str = js_string(val)
        out.append(
            f"  {{ name: {js_string(v['name'])}, category: {js_string('use')}, value: {val_str}, type: {js_string(v['resolvedType'])} }},\n"
        )
    out.append("];\n")
    return "".join(out)


# ----------------------- generic float -----------------------


def emit_float_tokens(name: str, collection_key: str, collections: dict[str, list[dict]]) -> str:
    rows = []
    for v in collections[collection_key]:
        m = v["valuesByMode"]["Mode 1"]
        val = m["value"]
        alias = m.get("alias")
        rows.append(
            f"  {{ name: {js_string(v['name'])}, value: {val}, alias: {js_string(alias)} }},"
        )
    return f"export const {name}: FloatToken[] = [\n" + "\n".join(rows) + "\n];\n\n"


def build_spacing(collections: dict[str, list[dict]]) -> str:
    out = [HEADER]
    out.append("export type FloatToken = {\n  name: string;\n  value: number;\n  alias: string | null;\n};\n\n")
    out.append(emit_float_tokens("baseScale", "token", collections))
    out.append(emit_float_tokens("paddingTokens", "padding", collections))
    out.append(emit_float_tokens("marginTokens", "margin", collections))
    out.append(emit_float_tokens("gapTokens", "gap", collections))
    out.append(emit_float_tokens("spaceTokens", "space", collections))
    return "".join(out)


def build_sizing(collections: dict[str, list[dict]]) -> str:
    out = [HEADER]
    out.append("export type FloatToken = {\n  name: string;\n  value: number;\n  alias: string | null;\n};\n\n")
    out.append(emit_float_tokens("heightTokens", "height", collections))
    out.append(emit_float_tokens("maxHeightTokens", "max-height", collections))
    out.append(emit_float_tokens("maxWidthTokens", "max-width", collections))
    return "".join(out)


def build_borders(collections: dict[str, list[dict]]) -> str:
    out = [HEADER]
    out.append("export type FloatToken = {\n  name: string;\n  value: number;\n  alias: string | null;\n};\n\n")
    out.append(emit_float_tokens("borderRadiusTokens", "border-radius", collections))
    out.append(emit_float_tokens("borderWidthTokens", "border-width", collections))
    return "".join(out)


def build_effects(collections: dict[str, list[dict]]) -> str:
    out = [HEADER]
    out.append("export type FloatToken = {\n  name: string;\n  value: number;\n  alias: string | null;\n};\n\n")
    out.append(emit_float_tokens("opacityTokens", "opacity", collections))
    out.append(emit_float_tokens("strokeWidthTokens", "stroke-width", collections))
    return "".join(out)


# ----------------------- summary -----------------------


def build_summary(collections: dict[str, list[dict]]) -> str:
    out = [HEADER]
    out.append("export type TokenCollectionSummary = {\n  name: string;\n  count: number;\n  type: string;\n};\n\n")
    out.append("export const collectionSummary: TokenCollectionSummary[] = [\n")
    for name, items in collections.items():
        # representative type
        rtype = items[0]["resolvedType"]
        out.append(
            f"  {{ name: {js_string(name)}, count: {len(items)}, type: {js_string(rtype)} }},\n"
        )
    out.append("];\n\n")
    total = sum(len(v) for v in collections.values())
    out.append(f"export const totalTokens = {total};\n")
    return "".join(out)


def main() -> None:
    collections = load_collections()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    (OUT_DIR / "colors.ts").write_text(build_colors(collections))
    (OUT_DIR / "typography.ts").write_text(build_typography(collections))
    (OUT_DIR / "spacing.ts").write_text(build_spacing(collections))
    (OUT_DIR / "sizing.ts").write_text(build_sizing(collections))
    (OUT_DIR / "borders.ts").write_text(build_borders(collections))
    (OUT_DIR / "effects.ts").write_text(build_effects(collections))
    (OUT_DIR / "summary.ts").write_text(build_summary(collections))

    total = sum(len(v) for v in collections.values())
    print(f"Wrote token data to {OUT_DIR}/")
    print(f"Total tokens: {total}")
    for name, items in collections.items():
        print(f"  {name}: {len(items)}")


if __name__ == "__main__":
    main()
