#!/usr/bin/env python3
"""
sync-tokens.py — generate app/globals.css from references/variables-export.json

Reads the Figma variables export (shadcn/ui collection, 4 modes) and writes a
complete Tailwind v4 globals.css that defines all theme tokens for:
  :root                  — Light mode (default)
  .dark                  — Dark mode
  [data-theme="primary"] — Primary (blue)
  [data-theme="secondary"]— Secondary (yellow)

Usage:
  python sync-tokens.py                                  # print to stdout
  python sync-tokens.py --output ../../../../app/globals.css   # write file
  python sync-tokens.py --json ./refs/variables-export.json    # custom source

After running, components reference these tokens via Tailwind utilities such as
`bg-background`, `text-foreground`, `border-border`, etc.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_JSON = SCRIPT_DIR.parent / "references" / "variables-export.json"

MODES = ["Light mode", "Dark mode", "Primary", "Secondary"]
SELECTORS = {
    "Light mode": ":root",
    "Dark mode": ".dark",
    "Primary": '[data-theme="primary"]',
    "Secondary": '[data-theme="secondary"]',
}

# Order in which CSS variables are emitted (matches shadcn/ui convention).
TOKEN_ORDER = [
    "background", "foreground",
    "card", "card-foreground",
    "popover", "popover-foreground",
    "primary", "primary-foreground",
    "secondary", "secondary-foreground",
    "muted", "muted-foreground",
    "accent", "accent-foreground",
    "destructive",
    "border", "input", "ring",
    "chart-1", "chart-2", "chart-3", "chart-4", "chart-5",
    "sidebar", "sidebar-foreground",
    "sidebar-primary", "sidebar-primary-foreground",
    "sidebar-accent", "sidebar-accent-foreground",
    "sidebar-border", "sidebar-ring",
]

HEADER = '''/* app/globals.css — generated by sync-tokens.py. DO NOT EDIT BY HAND.
 * Source: .claude/skills/shadcn-ui-design/references/variables-export.json
 * Re-run: python .claude/skills/shadcn-ui-design/scripts/sync-tokens.py --output app/globals.css
 */

@import "tailwindcss";

/* Map CSS variables → Tailwind v4 utility classes */
@theme {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
  --font-family-sans: var(--font-sans);
  --font-family-mono: var(--font-mono);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}
'''

FONT_BLOCK = '''    --radius: 0.5rem;
    --font-sans: "Inter", sans-serif;
    --font-mono: "Geist Mono", monospace;
    --font-thai: "IBM Plex Sans Thai", sans-serif;'''


def rgba_to_hex(value: dict) -> str:
    r = round(value["r"] * 255)
    g = round(value["g"] * 255)
    b = round(value["b"] * 255)
    a = value.get("a", 1)
    if a < 1:
        return f"#{r:02X}{g:02X}{b:02X}{round(a * 255):02X}"
    return f"#{r:02X}{g:02X}{b:02X}"


def load_shadcn_vars(json_path: Path) -> dict[str, dict[str, str]]:
    """Return {token_name: {mode_name: hex_value}}."""
    with json_path.open() as f:
        data = json.load(f)

    tokens: dict[str, dict[str, str]] = {}
    for v in data["variables"]:
        if v.get("collectionName") != "shadcn/ui":
            continue
        if v.get("resolvedType") != "COLOR":
            continue
        name = v["name"]
        per_mode = {}
        for mode in MODES:
            entry = v["valuesByMode"].get(mode)
            if not entry:
                continue
            per_mode[mode] = rgba_to_hex(entry["value"])
        tokens[name] = per_mode
    return tokens


def render_theme_block(selector: str, mode: str, tokens: dict[str, dict[str, str]], include_fonts: bool) -> str:
    lines = [f"  {selector} {{"]
    for name in TOKEN_ORDER:
        per_mode = tokens.get(name)
        if not per_mode or mode not in per_mode:
            continue
        lines.append(f"    --{name}: {per_mode[mode]};")
    # Emit any extra tokens not in TOKEN_ORDER (forward-compatibility)
    for name, per_mode in tokens.items():
        if name in TOKEN_ORDER or mode not in per_mode:
            continue
        lines.append(f"    --{name}: {per_mode[mode]};")
    if include_fonts:
        lines.append(FONT_BLOCK)
    lines.append("  }")
    return "\n".join(lines)


def render_globals_css(tokens: dict[str, dict[str, str]]) -> str:
    parts = [HEADER, "", "@layer base {"]
    for i, mode in enumerate(MODES):
        block = render_theme_block(SELECTORS[mode], mode, tokens, include_fonts=(i == 0))
        parts.append(f"  /* {mode} */")
        parts.append(block)
        parts.append("")
    parts.append("}")
    parts.append("")
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync shadcn/ui tokens from Figma export to globals.css")
    ap.add_argument("--json", type=Path, default=DEFAULT_JSON, help="Path to variables-export.json")
    ap.add_argument("--output", type=Path, default=None, help="Write to this file (default: stdout)")
    args = ap.parse_args()

    if not args.json.exists():
        print(f"error: {args.json} not found", file=sys.stderr)
        return 1

    tokens = load_shadcn_vars(args.json)
    if not tokens:
        print("error: no shadcn/ui COLOR tokens found in export", file=sys.stderr)
        return 1

    css = render_globals_css(tokens)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(css)
        print(f"wrote {len(css)} bytes → {args.output} ({len(tokens)} tokens × {len(MODES)} themes)", file=sys.stderr)
    else:
        sys.stdout.write(css)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
